from pygame.locals import *

GAME_NAME = "Shmuppy"
GAME_VER = ""

# Options
RESOLUTION = (600,800)
FULL_SCREEN = False
FPS = 60.0

# Debugging
PROFILE = False

# Controls
PLAYER_COLOR = (255,0,0)
PLAYER_SIZE = (24,24)
PLAYER_UP = K_UP
PLAYER_DOWN = K_DOWN
PLAYER_LEFT = K_LEFT
PLAYER_RIGHT = K_RIGHT
PLAYER_MOVE_KEYS = (PLAYER_UP, PLAYER_RIGHT, PLAYER_DOWN, PLAYER_LEFT)
MOVE_OFFSET = 60/FPS*2
MOVE_UP = [ 0, -MOVE_OFFSET ]
MOVE_DOWN = [ 0, MOVE_OFFSET ]
MOVE_LEFT = [ -MOVE_OFFSET, 0 ]
MOVE_RIGHT = [ MOVE_OFFSET, 0 ]
KEYMAP = {
    PLAYER_UP:      MOVE_UP,
    PLAYER_DOWN:    MOVE_DOWN,
    PLAYER_LEFT:    MOVE_LEFT,
    PLAYER_RIGHT:   MOVE_RIGHT }

# Ememies
ENEMY_COLOR = (0,50,0)
ENEMY_SIZE = (24,24)
ENEMY_POSITION = (RESOLUTION[0]/2, RESOLUTION[1]/2)

# Room
BGCOLOR = (0,20,20)
SCREEN_RECT = (0, 0, RESOLUTION[0], RESOLUTION[1])
TILE_SIZE = (32,32)
ROOM_TILES = [ RESOLUTION[0] / TILE_SIZE[0], RESOLUTION[1] / TILE_SIZE[1] ]
