from pygame.locals import *

GAME_NAME = "Shmuppy"
GAME_VER = ""

# Options
RESOLUTION = (600,800)
FULL_SCREEN = False
FPS = 60.0

# Debugging
PROFILE = False

# Controls
UP = K_UP
DOWN = K_DOWN
LEFT = K_LEFT
RIGHT = K_RIGHT
MOVE_OFFSET = 60/FPS*2

# Player
PLAYER_COLOR = (255,0,0)
PLAYER_SIZE = (24,24)

# Ememies
ENEMY_COLOR = (0,50,0)
ENEMY_SIZE = (24,24)
ENEMY_POSITION = (RESOLUTION[0]/2, RESOLUTION[1]/2)

# Room
BGCOLOR = (0,20,20)
SCREEN_RECT = (0, 0, RESOLUTION[0], RESOLUTION[1])
TILE_SIZE = (32,32)
ROOM_TILES = [ RESOLUTION[0] / TILE_SIZE[0], RESOLUTION[1] / TILE_SIZE[1] ]
